<?php 
$_code=$this->getMethodCode(); 
$methods= $this->getAllowedMethods();
$emiBanks= $this->getBankNames('emi_bank_names');
$netBanks= $this->getBankNames('net_bank_names');
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li class="message">
        <?php echo $this->getRedirectMessage();?>
    </li>
    <!-- <li>
        <label for="<?php //echo $_code ?>_payment_method" class="required"><em>*</em><?php //echo $this->__('Payment Method') ?></label>
        <div class="input-box">
            <select title="<?php //echo $this->__('Payment Method') ?>" class="input-select required-entry" id="<?php //echo $_code ?>_payment_method" name="payment[PinePG_payment_method]" value="<?php //echo $this->htmlEscape($this->getInfoData(//'PinePG_payment_method')) ?>" onchange="hideMethod()">
                <option value=""><?php //echo $this->__('--Please Select--')?></option>
                <?php //foreach($methods as $method):?>
                    <option value="<?php //echo $method['value']?>"><?php //echo $method['label']?></option>
                <?php //endforeach;?>    
            </select>
        </div>
    </li>
    <li id="zippy_bank_name" style="display:none;">
        <label for="<?php //echo $_code ?>_bank_name" class="required"><em>*</em><?php //echo $this->__(//'Bank Name') ?></label>
        <div class="input-box">
            <select title="<?php //echo $this->__('Bank Name') ?>" class="input-select required-entry" id="<?php //echo $_code ?>_bank_name" name="payment[PinePG_bank_name]" value="<?php //echo $this->htmlEscape($this->getInfoData('PinePG_bank_name')) ?>">
              <?php //echo $emiBanks;?>
            </select>
        </div>
    </li>
    <li id="zippy_emi_months" style="display:none;">
        <label for="<?php //echo $_code ?>_emi_months" class="required"><em>*</em><?php //echo $this->__('EMI Months') ?></label>
        <div class="input-box">
            <select title="<?php //echo $this->__('EMI Months') ?>" class="input-select required-entry" id="<?php //echo $_code ?>_payment_method" name="payment[PinePG_emi_months]" value="<?php ///echo $this->htmlEscape($this->getInfoData('PinePG_emi_months')) ?>">
                <option value="3">3</option>
                <option value="6">6</option>
                <option value="9">9</option>
                <option value="12">12</option>
            </select>
        </div>
    </li> -->
</ul>
 <script>
// function hideMethod()
// {
//     var emibankNames = '<?php echo $emiBanks?>';
//     var netbankNames = '<?php echo $netBanks?>';
//     var emiMonths = document.getElementById("zippy_emi_months");
//     var bankName = document.getElementById("zippy_bank_name");
//     var bankNameSelect = document.getElementById("<?php echo $_code ?>_bank_name");
//     var paymentMethod = document.getElementById("PinePG_payment_method");
//     if(paymentMethod.options[paymentMethod.selectedIndex].value == "EMI")
//     {
//         emiMonths.style.display="block";
//         bankNameSelect.innerHTML = '';
//         bankNameSelect.innerHTML = emibankNames;
//         bankName.style.display="block"; 
//     }
    
//     if(paymentMethod.options[paymentMethod.selectedIndex].value == "NET")
//     {
//         emiMonths.style.display="none"; 
//         bankNameSelect.innerHTML = '';
//         bankNameSelect.innerHTML = netbankNames;
//         bankName.style.display="block"; 
      

//     }
    
//     if(paymentMethod.options[paymentMethod.selectedIndex].value != "NET" && paymentMethod.options[paymentMethod.selectedIndex].value != "EMI")
//     {
//         emiMonths.style.display="none"; 
//         bankName.style.display="none"; 

//     }
    
    
// }
 </script>